version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/files/pe_mcp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
